### PR TITLE
Include More Amazon Domains and Formatting Changes

### PR DESCRIPTION
**Pull request by dtsdwarak**
Hi,

Thanks for the extension. It is such a time-saver. I noticed a few Amazon domains missing and thought I'd fix them.

Please verify the details and if all check out okay.

### CODE REVIEW

**Comment by berezovskyi** [comment]
Just tested as an unpacked extension and can confirm that it works on amazon.se now.

**Comment by dtsdwarak** [comment]
Thanks for testing @berezovskyi

**Comment by rubenmv** [comment]
Thank you for your corrections and sorry for the big delay (4 months!). I just merged it with some other changes and pushed a new version to the store.

**Comment by dtsdwarak** [comment]
Thanks @rubenmv for pushing the changes. There is a new pull request #15 that goes over this pull request.

Also, the changes haven't reached the Firefox Addon store. Could you please check on that?
https://addons.mozilla.org/en-US/firefox/addon/goodreads-ratings-for-amazon/versions/

**Pull request merged**
